config {
    type: 'table',
    database:'secure-potion-409606',
    schema:'harika_dataset',
    name: 'orgtbl',
    tags:['newone']

}

BEGIN

declare tblvalue string;
declare sqlquery string;


set sqlquery=
"select t1.id,t1.age,t1.country,t1.city from ${ref("info1")} t1 inner join ${ref("info2")} t2 on t1.id=t2.id";

set tblvalue = sqlquery;

EXECUTE IMMEDIATE tblvalue;

END