config {
    database: 'secure-potion-409606',
    schema: "Results",
    type: "table",
    name: "workflow_query",
    dependencies: ['workflow_join'],
    tags : ['airflow']
}

SELECT 
    name,
    age,
    city,
    country,
    department,
    salary,
    qualification,
    courses,
    experience,
    previous_company
FROM 
    ${ref('workflow_join')}
WHERE 
    country IN ('USA', 'Canada', 'UK','China')
    AND salary > 45000
ORDER BY 
    salary DESC
